name: dhttpd
description: A static file HTTP server for easy directory serving.
version: 3.0.0-dev
homepage: https://github.com/kevmoo/dhttpd
authors:
- Seth Ladd <sethladd@gmail.com>
- Kevin Moore <github@j832.com>

environment:
  sdk: ">=2.0.0-dev.48.0 <2.0.0"

dependencies:
  args: ">=0.12.0+1 <2.0.0"
  build_cli_annotations: ^0.1.0
  shelf: ^0.7.2
  shelf_static: ^0.2.0

dev_dependencies:
  build_cli: ^0.2.0
  build_runner: ^0.8.2
  test: ^0.12.34
  test_process: ^1.0.1

executables:
  dhttpd:
